-- Run this script in your Supabase SQL Editor to create the bills table

CREATE TABLE IF NOT EXISTS public.bills (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id TEXT,
  booking_id TEXT,
  guest_name TEXT,
  guest_phone TEXT,
  guest_email TEXT,
  guest_address TEXT,
  guest_gst TEXT,
  check_in TEXT,
  check_out TEXT,
  rooms_data JSONB,
  base_price NUMERIC,
  gst_amount NUMERIC,
  dsda_charge NUMERIC,
  total_amount NUMERIC,
  bill_type TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.bills ENABLE ROW LEVEL SECURITY;

-- Create policies (allow all for anon key since it's a simple app, adjust as needed)
CREATE POLICY "Allow anonymous read access on bills" ON public.bills FOR SELECT USING (true);
CREATE POLICY "Allow anonymous insert access on bills" ON public.bills FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow anonymous update access on bills" ON public.bills FOR UPDATE USING (true);
CREATE POLICY "Allow anonymous delete access on bills" ON public.bills FOR DELETE USING (true);
